[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "researcher_aggregator"
version = "0.0"

dependencies = [
    "pytest",
    "requests",
    "pandas",
    "xmltodict",
]

[tool.setuptools.packages.find]
where = ["src"]
